package com.casino.casinoerp;
import com.casino.casinoerp.dto.CrmDtos.*;import com.casino.casinoerp.entity.*;import com.casino.casinoerp.repository.*;import com.casino.casinoerp.service.*;import com.casino.casinoerp.security.Role;
import com.fasterxml.jackson.databind.json.JsonMapper;import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import org.junit.jupiter.api.*;import java.time.*;import java.math.*;import java.util.*;
import static org.mockito.Mockito.*;import static org.mockito.ArgumentMatchers.*;import static org.assertj.core.api.Assertions.*;
class CrmServiceTests {
 CrmRepository repo=mock(CrmRepository.class);CustomerRepository customers=mock(CustomerRepository.class);CustomerSessionRepository sessions=mock(CustomerSessionRepository.class);CurrentUserRoleService roles=mock(CurrentUserRoleService.class);AuthenticatedUserService users=mock(AuthenticatedUserService.class);BusinessDateRepository dates=mock(BusinessDateRepository.class);BusinessDateService clock=mock(BusinessDateService.class);SystemLockService locks=mock(SystemLockService.class);AuditLogService audit=mock(AuditLogService.class);
 CrmService service=new CrmService(repo,customers,sessions,roles,users,dates,clock,locks,audit,JsonMapper.builder().addModule(new JavaTimeModule()).build());
 UUID customer=UUID.randomUUID(),actor=UUID.randomUUID(),id=UUID.randomUUID();
 ServiceCreate request(UUID session){return new ServiceCreate(customer,session,ServiceType.GIFT,"Gift",LocalDateTime.of(2025,1,1,12,0),null,Classification.UNSPECIFIED,null,"key");}
 @BeforeEach void setup(){when(repo.replay(anyBoolean(),anyString())).thenReturn(null);when(roles.getCurrentRole()).thenReturn(Optional.of(Role.SUPER_ADMIN));User u=new User();u.setId(actor);when(users.getRequiredUser()).thenReturn(u);when(customers.findById(customer)).thenReturn(Optional.of(new Customer()));when(dates.findByStatus("OPEN")).thenReturn(List.of());when(clock.currentCasinoDateTime()).thenReturn(LocalDateTime.of(2026,9,15,12,0));when(repo.create(any(ServiceCreate.class),eq(actor),nullable(LocalDate.class),any(),any())).thenReturn(id);}
 @Test void historicalServiceNoOpenDateOrSessionRequired(){assertThat(service.create(request(null)).get("id")).isEqualTo(id);verify(repo).create(eq(request(null)),eq(actor),isNull(),any(),any());verifyNoInteractions(sessions);}
 @Test void directorCannotMutateEvenDirectServiceCall(){when(roles.getCurrentRole()).thenReturn(Optional.of(Role.DIRECTOR));assertThatThrownBy(()->service.create(request(null))).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);verifyNoInteractions(repo);}
 @Test void customerMustExist(){when(customers.findById(customer)).thenReturn(Optional.empty());assertThatThrownBy(()->service.create(request(null))).hasMessageContaining("Customer not found");verify(repo,never()).create(any(ServiceCreate.class),any(),any(),any(),any());}
 @Test void sessionOwnershipRequiredButClosedHistoricalAllowed(){UUID sid=UUID.randomUUID();CustomerSession session=new CustomerSession();session.setCustomerId(UUID.randomUUID());when(sessions.findById(sid)).thenReturn(Optional.of(session));assertThatThrownBy(()->service.create(request(sid))).hasMessageContaining("another customer");session.setCustomerId(customer);session.setStatus("CLOSED");service.create(request(sid));}
 @Test void recordingDateDoesNotReplaceServiceTime(){BusinessDate d=new BusinessDate();d.setBusinessDate(LocalDate.of(2026,9,15));when(dates.findByStatus("OPEN")).thenReturn(List.of(d));service.create(request(null));verify(repo).create(eq(request(null)),eq(actor),eq(d.getBusinessDate()),any(),any());}
 @Test void replayDoesNotWriteOrAudit(){service.create(request(null));var cap=org.mockito.ArgumentCaptor.forClass(String.class);verify(repo).create(any(ServiceCreate.class),any(),isNull(),any(),cap.capture());clearInvocations(repo,audit);when(repo.replay(false,"key")).thenReturn(Map.of("id",id,"request_signature",cap.getValue()));assertThat(service.create(request(null)).get("replayed")).isEqualTo(true);verify(repo,never()).create(any(ServiceCreate.class),any(),any(),any(),any());verifyNoInteractions(audit);}
 @Test void conflictingReplayRejected(){when(repo.replay(false,"key")).thenReturn(Map.of("id",id,"request_signature","other"));assertThatThrownBy(()->service.create(request(null))).hasMessageContaining("different record");}
 @Test void filtersAndStatusesValidated(){assertThatThrownBy(()->service.history("","BONUS","",null,null)).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->service.change(false,id,new Change("APPROVED",0L))).isInstanceOf(IllegalArgumentException.class);when(repo.change(eq(true),eq(id),any(),any())).thenReturn(0);assertThatThrownBy(()->service.change(true,id,new Change("COMPLETED",0L))).hasMessageContaining("changed");}
 @Test void allUnrelatedRolesDeniedAtServiceBoundary(){for(Role role:Role.values()){if(role==Role.SUPER_ADMIN||role==Role.DIRECTOR)continue;when(roles.getCurrentRole()).thenReturn(Optional.of(role));assertThatThrownBy(()->service.history("","","",null,null)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);assertThatThrownBy(()->service.create(request(null))).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);}when(roles.getCurrentRole()).thenReturn(Optional.empty());assertThatThrownBy(()->service.history("","","",null,null)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);}
 @Test void legacyCreateCannotOverwriteCrmRecord(){var legacyRepo=mock(CustomerServiceRecordRepository.class);var legacyService=new CustomerServiceRecordService(legacyRepo,clock,locks,audit,roles);var record=new CustomerServiceRecord();record.setId(id);assertThatThrownBy(()->legacyService.save(record)).hasMessageContaining("must not supply an ID");verifyNoInteractions(legacyRepo);}
 @Test void rolloverNeverRewritesActualServiceTime(){var first=new BusinessDate();first.setBusinessDate(LocalDate.of(2026,9,14));var second=new BusinessDate();second.setBusinessDate(LocalDate.of(2026,9,15));when(dates.findByStatus("OPEN")).thenReturn(List.of(first),List.of(second));var request=new ServiceCreate(customer,null,ServiceType.OTHER,"Overnight",LocalDateTime.of(2026,9,15,8,30),BigDecimal.ZERO,Classification.UNSPECIFIED,null,"overnight");service.create(request);service.create(new ServiceCreate(customer,null,request.serviceType(),request.description(),request.serviceAt(),request.cost(),request.classification(),null,"next-date"));var capture=org.mockito.ArgumentCaptor.forClass(ServiceCreate.class);verify(repo,times(2)).create(capture.capture(),eq(actor),any(),any(),any());assertThat(capture.getAllValues()).allSatisfy(v->assertThat(v.serviceAt()).isEqualTo(request.serviceAt()));}
 @Test void historicReadWithoutOpenDate(){when(repo.history("","","",null,null)).thenReturn(List.of());var result=service.history("","","",null,null);assertThat(result.recordingBusinessDate()).isNull();assertThat(result.limit()).isEqualTo(100);assertThat(result.records()).isEmpty();}
}
