package com.casino.casinoerp;

import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.transaction.annotation.Transactional;
import java.sql.*;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;

@SpringBootTest class HrShiftRosterMigrationTests {
    @Autowired JdbcTemplate jdbc;
    @Test void v27TablesConstraintsAndForeignKeysInstalled(){assertThat(table("shift_definitions")).isTrue();assertThat(table("staff_roster_assignments")).isTrue();assertThat(constraint("staff_roster_assignments","staff_roster_assignments_staff_profile_id_fkey")).contains("staff_profiles(id)");assertThat(constraint("staff_roster_assignments","staff_roster_assignments_shift_definition_id_fkey")).contains("shift_definitions(id)");assertThat(index("uq_staff_roster_scheduled_staff_date")).contains("UNIQUE").contains("WHERE").contains("SCHEDULED");}
    @Test @Transactional void databaseEnforcesCanonicalUniqueShiftCode(){insertShift("TEST_CANONICAL",LocalTime.of(13,0),LocalTime.of(23,0),false,0,0);assertThatThrownBy(()->insertShift("TEST_CANONICAL",LocalTime.of(14,0),LocalTime.of(22,0),false,0,0)).isInstanceOf(DataIntegrityViolationException.class);}
    @Test @Transactional void databaseRejectsNonCanonicalCode(){assertThatThrownBy(()->insertShift(" test ",LocalTime.of(13,0),LocalTime.of(23,0),false,0,0)).isInstanceOf(DataIntegrityViolationException.class);}
    @Test @Transactional void databaseRejectsNegativeGrace(){assertThatThrownBy(()->insertShift("TEST_NEGATIVE",LocalTime.of(13,0),LocalTime.of(23,0),false,-1,0)).isInstanceOf(DataIntegrityViolationException.class);}
    @Test @Transactional void databaseRejectsEqualShiftTimes(){assertThatThrownBy(()->insertShift("TEST_EQUAL",LocalTime.of(13,0),LocalTime.of(13,0),false,0,0)).isInstanceOf(DataIntegrityViolationException.class);}
    @Test @Transactional void databaseRejectsDayShiftMarkedCrossMidnight(){assertThatThrownBy(()->insertShift("TEST_DAY_DIRECTION",LocalTime.of(13,0),LocalTime.of(23,0),true,0,0)).isInstanceOf(DataIntegrityViolationException.class);}
    @Test @Transactional void databaseRejectsNightShiftWithoutCrossMidnight(){assertThatThrownBy(()->insertShift("TEST_NIGHT_DIRECTION",LocalTime.of(18,0),LocalTime.of(3,30),false,0,0)).isInstanceOf(DataIntegrityViolationException.class);}
    @Test @Transactional void databaseRejectsInvalidRosterStatus(){Fixture f=fixture("BAD_STATUS");assertThatThrownBy(()->insertRoster(f.staff(),f.shift(),LocalDate.of(2099,1,1),"UNKNOWN",null)).isInstanceOf(DataIntegrityViolationException.class);}
    @Test @Transactional void scheduledSameDateUniqueButCancelledHistoryAndReplacementAllowed(){Fixture f=fixture("REPLACEMENT");LocalDate date=LocalDate.of(2099,2,1);assertThat(insertRoster(f.staff(),f.shift(),date,"CANCELLED","cancelled")).isEqualTo(1);assertThat(insertRoster(f.staff(),f.shift(),date,"SCHEDULED",null)).isEqualTo(1);assertThatThrownBy(()->insertRoster(f.staff(),f.shift(),date,"SCHEDULED",null)).isInstanceOf(DataIntegrityViolationException.class);}
    private boolean table(String name){return Boolean.TRUE.equals(jdbc.queryForObject("select exists(select 1 from information_schema.tables where table_schema='casino' and table_name=?)",Boolean.class,name));}private String constraint(String table,String name){return jdbc.queryForObject("select pg_get_constraintdef(oid) from pg_constraint where conrelid=('casino.'||?)::regclass and conname=?",String.class,table,name);}private String index(String name){return jdbc.queryForObject("select indexdef from pg_indexes where schemaname='casino' and indexname=?",String.class,name);}
    private UUID insertShift(String code,LocalTime start,LocalTime end,boolean crosses,int late,int early){UUID id=UUID.randomUUID();jdbc.update("insert into casino.shift_definitions(id,code,name,start_time,end_time,crosses_midnight,late_grace_minutes,early_check_in_minutes,active,created_at,updated_at) values(?,?,?,?,?,?,?,?,true,?,?)",id,code,code,Time.valueOf(start),Time.valueOf(end),crosses,late,early,Timestamp.valueOf(LocalDateTime.now()),Timestamp.valueOf(LocalDateTime.now()));return id;}
    private Fixture fixture(String suffix){UUID department=UUID.randomUUID(),title=UUID.randomUUID(),staff=UUID.randomUUID();UUID user=jdbc.queryForObject("select id from core.users order by created_at limit 1",UUID.class);Timestamp now=Timestamp.valueOf(LocalDateTime.now());jdbc.update("insert into casino.departments(id,code,name,active,created_at,updated_at) values(?,?,?,true,?,?)",department,"TEST_ROSTER_DEPT_"+suffix,"Department",now,now);jdbc.update("insert into casino.job_titles(id,code,name,active,created_at,updated_at) values(?,?,?,true,?,?)",title,"TEST_ROSTER_TITLE_"+suffix,"Title",now,now);jdbc.update("insert into casino.staff_profiles(id,user_id,employee_code,department_id,job_title_id,employment_status,employment_type,date_of_joining,created_at,updated_at) values(?,?,?,?,?,'ACTIVE','FULL_TIME',?,?,?)",staff,user,"TEST-ROSTER-"+suffix,department,title,java.sql.Date.valueOf(LocalDate.now()),now,now);return new Fixture(staff,insertShift("TEST_SHIFT_"+suffix,LocalTime.of(18,0),LocalTime.of(3,30),true,0,0));}
    private int insertRoster(UUID staff,UUID shift,LocalDate date,String status,String reason){Timestamp now=Timestamp.valueOf(LocalDateTime.now());UUID actor=jdbc.queryForObject("select id from core.users order by created_at limit 1",UUID.class);return jdbc.update("insert into casino.staff_roster_assignments(id,staff_profile_id,shift_definition_id,roster_date,status,cancellation_reason,cancelled_by,cancelled_at,created_at,updated_at) values(?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),staff,shift,java.sql.Date.valueOf(date),status,reason,"CANCELLED".equals(status)?actor:null,"CANCELLED".equals(status)?now:null,now,now);}private record Fixture(UUID staff,UUID shift){}
}
