package com.casino.casinoerp;

import com.casino.casinoerp.dto.*;import com.casino.casinoerp.entity.*;import com.casino.casinoerp.repository.*;import com.casino.casinoerp.security.Role;import com.casino.casinoerp.service.*;
import org.junit.jupiter.api.*;import org.springframework.dao.DataIntegrityViolationException;import java.time.*;import java.util.*;
import org.mockito.InOrder;
import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;

class StaffRosterServiceTests {
    private final StaffRosterAssignmentRepository rosters=mock(StaffRosterAssignmentRepository.class);private final StaffProfileRepository profiles=mock(StaffProfileRepository.class);private final ShiftDefinitionRepository shifts=mock(ShiftDefinitionRepository.class);private final StaffLeaveRequestRepository leaveRequests=mock(StaffLeaveRequestRepository.class);private final UserRepository users=mock(UserRepository.class);private final AuthenticatedUserService auth=mock(AuthenticatedUserService.class);private final CurrentUserRoleService roles=mock(CurrentUserRoleService.class);private final AuditLogService audit=mock(AuditLogService.class);private final StaffRosterService service=new StaffRosterService(rosters,profiles,shifts,leaveRequests,users,auth,roles,new RolePermissionService(),audit);
    private final UUID staffId=UUID.randomUUID(),userId=UUID.randomUUID(),shiftId=UUID.randomUUID(),actorId=UUID.randomUUID();private final LocalDate date=LocalDate.of(2026,9,10);
    @BeforeEach void setup(){when(roles.getCurrentRole()).thenReturn(Optional.of(Role.DIRECTOR));when(profiles.findById(staffId)).thenReturn(Optional.of(staff(EmploymentStatus.ACTIVE)));when(profiles.findByIdForUpdate(staffId)).thenReturn(Optional.of(staff(EmploymentStatus.ACTIVE)));when(shifts.findById(shiftId)).thenReturn(Optional.of(shift(shiftId,"DAY",LocalTime.of(13,0),LocalTime.of(23,0),false,true)));when(leaveRequests.findByStaffAndStatusOverlappingDates(any(),eq(LeaveRequestStatus.APPROVED),any(),any())).thenReturn(List.of());when(rosters.findByStaffProfileIdAndStatusAndRosterDateBetweenOrderByRosterDateAsc(any(),eq(RosterStatus.SCHEDULED),any(),any())).thenReturn(List.of());User actor=user(actorId,"director");when(auth.getRequiredUser()).thenReturn(actor);when(users.findById(userId)).thenReturn(Optional.of(user(userId,"employee")));when(rosters.saveAndFlush(any())).thenAnswer(i->{StaffRosterAssignment v=i.getArgument(0);if(v.getId()==null)v.setId(UUID.randomUUID());return v;});when(rosters.save(any())).thenAnswer(i->i.getArgument(0));}
    @Test void activeStaffAndActiveShiftAreScheduled(){var result=service.create(request(shiftId,date));assertThat(result.status()).isEqualTo(RosterStatus.SCHEDULED);assertThat(result.scheduledStart()).isEqualTo(date.atTime(13,0));assertThat(result.scheduledEnd()).isEqualTo(date.atTime(23,0));verify(audit).log(eq("CREATE_STAFF_ROSTER"),eq("HR"),any(),eq(actorId),contains("EMP-1"));}
    @Test void nonActiveEmploymentStatusesRejected(){for(EmploymentStatus status:List.of(EmploymentStatus.SUSPENDED,EmploymentStatus.INACTIVE,EmploymentStatus.TERMINATED)){when(profiles.findByIdForUpdate(staffId)).thenReturn(Optional.of(staff(status)));assertThatThrownBy(()->service.create(request(shiftId,date))).hasMessageContaining("ACTIVE");}}
    @Test void inactiveShiftRejected(){when(shifts.findById(shiftId)).thenReturn(Optional.of(shift(shiftId,"DAY",LocalTime.of(13,0),LocalTime.of(23,0),false,false)));assertThatThrownBy(()->service.create(request(shiftId,date))).hasMessageContaining("must be ACTIVE");}
    @Test void sameDateRaceIsMappedToConflict(){doThrow(new DataIntegrityViolationException("constraint")).when(rosters).saveAndFlush(any());assertThatThrownBy(()->service.create(request(shiftId,date))).hasMessageContaining("already has a scheduled roster");}
    @Test void cancelledAssignmentDoesNotBlockReplacement(){StaffRosterAssignment cancelled=roster(UUID.randomUUID(),shiftId,date,RosterStatus.CANCELLED);when(rosters.findByStaffProfileIdAndStatusAndRosterDateBetweenOrderByRosterDateAsc(any(),eq(RosterStatus.SCHEDULED),any(),any())).thenReturn(List.of());assertThat(service.create(request(shiftId,date)).status()).isEqualTo(RosterStatus.SCHEDULED);}
    @Test void ordinarySameDayOverlapRejected(){UUID otherShift=UUID.randomUUID();ShiftDefinition existingShift=shift(otherShift,"OTHER",LocalTime.of(12,0),LocalTime.of(15,0),false,true);StaffRosterAssignment existing=roster(UUID.randomUUID(),otherShift,date,RosterStatus.SCHEDULED);when(shifts.findById(otherShift)).thenReturn(Optional.of(existingShift));when(rosters.findByStaffProfileIdAndStatusAndRosterDateBetweenOrderByRosterDateAsc(any(),eq(RosterStatus.SCHEDULED),any(),any())).thenReturn(List.of(existing));assertThatThrownBy(()->service.create(request(shiftId,date))).hasMessageContaining("overlaps");}
    @Test void crossMidnightOverlapOnNextRosterDateRejected(){UUID nightId=UUID.randomUUID();ShiftDefinition night=shift(nightId,"NIGHT",LocalTime.of(18,0),LocalTime.of(3,30),true,true);StaffRosterAssignment existing=roster(UUID.randomUUID(),nightId,date,RosterStatus.SCHEDULED);ShiftDefinition early=shift(shiftId,"EARLY",LocalTime.of(2,0),LocalTime.of(10,0),false,true);when(shifts.findById(nightId)).thenReturn(Optional.of(night));when(shifts.findById(shiftId)).thenReturn(Optional.of(early));when(rosters.findByStaffProfileIdAndStatusAndRosterDateBetweenOrderByRosterDateAsc(any(),eq(RosterStatus.SCHEDULED),any(),any())).thenReturn(List.of(existing));assertThatThrownBy(()->service.create(request(shiftId,date.plusDays(1)))).hasMessageContaining("overlaps");}
    @Test void adjacentIntervalsAreAccepted(){UUID firstId=UUID.randomUUID();ShiftDefinition first=shift(firstId,"FIRST",LocalTime.of(18,0),LocalTime.of(3,30),true,true);StaffRosterAssignment existing=roster(UUID.randomUUID(),firstId,date,RosterStatus.SCHEDULED);ShiftDefinition next=shift(shiftId,"NEXT",LocalTime.of(3,30),LocalTime.of(10,0),false,true);when(shifts.findById(firstId)).thenReturn(Optional.of(first));when(shifts.findById(shiftId)).thenReturn(Optional.of(next));when(rosters.findByStaffProfileIdAndStatusAndRosterDateBetweenOrderByRosterDateAsc(any(),eq(RosterStatus.SCHEDULED),any(),any())).thenReturn(List.of(existing));assertThat(service.create(request(shiftId,date.plusDays(1))).status()).isEqualTo(RosterStatus.SCHEDULED);}
    @Test void cancellationPreservesRecordAndReason(){UUID id=UUID.randomUUID();StaffRosterAssignment existing=roster(id,shiftId,date,RosterStatus.SCHEDULED);when(rosters.findById(id)).thenReturn(Optional.of(existing));var result=service.cancel(id,new CancelStaffRosterRequest(" staffing change "));assertThat(result.status()).isEqualTo(RosterStatus.CANCELLED);assertThat(result.cancellationReason()).isEqualTo("staffing change");verify(rosters).save(same(existing));verify(audit).log(eq("CANCEL_STAFF_ROSTER"),eq("HR"),eq(id),eq(actorId),contains("staffing change"));}
    @Test void updateRevalidatesOverlap(){UUID id=UUID.randomUUID(),otherId=UUID.randomUUID();StaffRosterAssignment current=roster(id,shiftId,date,RosterStatus.SCHEDULED),other=roster(otherId,shiftId,date.plusDays(1),RosterStatus.SCHEDULED);when(rosters.findById(id)).thenReturn(Optional.of(current));when(rosters.findByIdForUpdate(id)).thenReturn(Optional.of(current));when(rosters.findByStaffProfileIdAndStatusAndRosterDateBetweenOrderByRosterDateAsc(any(),eq(RosterStatus.SCHEDULED),any(),any())).thenReturn(List.of(current,other));assertThatThrownBy(()->service.update(id,new UpdateStaffRosterRequest(shiftId,date.plusDays(1),null))).hasMessageContaining("overlaps");}
    @Test void approvedLeaveBlocksSameDayRosterAndUsesCanonicalStatusQuery(){when(leaveRequests.findByStaffAndStatusOverlappingDates(staffId,LeaveRequestStatus.APPROVED,date,date)).thenReturn(List.of(leave(LeaveRequestStatus.APPROVED,date,date)));assertThatThrownBy(()->service.create(request(shiftId,date))).hasMessageContaining("approved leave");verify(rosters,never()).saveAndFlush(any());}
    @Test void approvedMultiDayLeaveBlocksRosterWithinRange(){when(leaveRequests.findByStaffAndStatusOverlappingDates(staffId,LeaveRequestStatus.APPROVED,date,date)).thenReturn(List.of(leave(LeaveRequestStatus.APPROVED,date.minusDays(2),date.plusDays(2))));assertThatThrownBy(()->service.create(request(shiftId,date))).hasMessageContaining("approved leave");}
    @Test void pendingRejectedAndCancelledLeaveCannotBlockRoster(){for(LeaveRequestStatus status:List.of(LeaveRequestStatus.PENDING,LeaveRequestStatus.REJECTED,LeaveRequestStatus.CANCELLED)){reset(leaveRequests);when(leaveRequests.findByStaffAndStatusOverlappingDates(staffId,LeaveRequestStatus.APPROVED,date,date)).thenReturn(List.of(leave(status,date,date)));assertThat(service.create(request(shiftId,date)).status()).isEqualTo(RosterStatus.SCHEDULED);verify(leaveRequests).findByStaffAndStatusOverlappingDates(staffId,LeaveRequestStatus.APPROVED,date,date);}}
    @Test void rosterBeforeOrAfterApprovedLeaveIsAllowedAtExactBoundaries(){when(leaveRequests.findByStaffAndStatusOverlappingDates(staffId,LeaveRequestStatus.APPROVED,date,date)).thenReturn(List.of(leave(LeaveRequestStatus.APPROVED,date.plusDays(1),date.plusDays(1))));assertThat(service.create(request(shiftId,date)).status()).isEqualTo(RosterStatus.SCHEDULED);reset(leaveRequests);when(leaveRequests.findByStaffAndStatusOverlappingDates(staffId,LeaveRequestStatus.APPROVED,date,date)).thenReturn(List.of(leave(LeaveRequestStatus.APPROVED,date.minusDays(1),date.minusDays(1))));assertThat(service.create(request(shiftId,date)).status()).isEqualTo(RosterStatus.SCHEDULED);}
    @Test void overnightRosterConflictsWithLeaveOnFollowingDay(){when(shifts.findById(shiftId)).thenReturn(Optional.of(shift(shiftId,"NIGHT",LocalTime.of(18,0),LocalTime.of(3,30),true,true)));when(leaveRequests.findByStaffAndStatusOverlappingDates(staffId,LeaveRequestStatus.APPROVED,date,date.plusDays(1))).thenReturn(List.of(leave(LeaveRequestStatus.APPROVED,date.plusDays(1),date.plusDays(1))));assertThatThrownBy(()->service.create(request(shiftId,date))).hasMessageContaining("approved leave");}
    @Test void rosterEndingExactlyAtLeaveMidnightDoesNotOverlap(){when(shifts.findById(shiftId)).thenReturn(Optional.of(shift(shiftId,"EVENING",LocalTime.of(18,0),LocalTime.MIDNIGHT,true,true)));assertThat(service.create(request(shiftId,date)).status()).isEqualTo(RosterStatus.SCHEDULED);verify(leaveRequests).findByStaffAndStatusOverlappingDates(staffId,LeaveRequestStatus.APPROVED,date,date);}
    @Test void updateIntoApprovedLeaveIsRejectedUnderStaffAndRosterLocks(){UUID id=UUID.randomUUID();StaffRosterAssignment current=roster(id,shiftId,date.minusDays(1),RosterStatus.SCHEDULED);when(rosters.findById(id)).thenReturn(Optional.of(current));when(rosters.findByIdForUpdate(id)).thenReturn(Optional.of(current));when(leaveRequests.findByStaffAndStatusOverlappingDates(staffId,LeaveRequestStatus.APPROVED,date,date)).thenReturn(List.of(leave(LeaveRequestStatus.APPROVED,date,date)));assertThatThrownBy(()->service.update(id,new UpdateStaffRosterRequest(shiftId,date,null))).hasMessageContaining("approved leave");InOrder order=inOrder(profiles,rosters);order.verify(profiles).findByIdForUpdate(staffId);order.verify(rosters).findByIdForUpdate(id);}
    @Test void updateOutsideApprovedLeaveIsAllowed(){UUID id=UUID.randomUUID();StaffRosterAssignment current=roster(id,shiftId,date.minusDays(1),RosterStatus.SCHEDULED);when(rosters.findById(id)).thenReturn(Optional.of(current));when(rosters.findByIdForUpdate(id)).thenReturn(Optional.of(current));assertThat(service.update(id,new UpdateStaffRosterRequest(shiftId,date,null)).rosterDate()).isEqualTo(date);}
    @Test void listBulkLoadsReferencesAndPreservesDetailContentAndFilters() {
        StaffRosterAssignment first=roster(UUID.randomUUID(),shiftId,date,RosterStatus.SCHEDULED);
        StaffRosterAssignment second=roster(UUID.randomUUID(),shiftId,date.plusDays(1),RosterStatus.SCHEDULED);
        ShiftDefinition night=shift(shiftId,"NIGHT",LocalTime.of(18,0),LocalTime.of(3,30),true,true);
        when(shifts.findById(shiftId)).thenReturn(Optional.of(night));
        when(rosters.findById(first.getId())).thenReturn(Optional.of(first));
        when(rosters.findById(second.getId())).thenReturn(Optional.of(second));
        var expected=List.of(service.get(first.getId()),service.get(second.getId()));
        UUID departmentId=UUID.randomUUID();
        when(rosters.search(date,date.plusDays(1),staffId,departmentId,shiftId,RosterStatus.SCHEDULED)).thenReturn(List.of(first,second));
        when(profiles.findAllById(Set.of(staffId))).thenReturn(List.of(staff(EmploymentStatus.ACTIVE)));
        when(shifts.findAllById(Set.of(shiftId))).thenReturn(List.of(night));
        when(users.findAllById(Set.of(userId))).thenReturn(List.of(user(userId,"employee")));
        clearInvocations(rosters,profiles,shifts,users);
        assertThat(service.list(date,date.plusDays(1),staffId,departmentId,shiftId,RosterStatus.SCHEDULED)).containsExactlyElementsOf(expected);
        verify(rosters).search(date,date.plusDays(1),staffId,departmentId,shiftId,RosterStatus.SCHEDULED);
        verify(profiles).findAllById(Set.of(staffId));
        verify(shifts).findAllById(Set.of(shiftId));
        verify(users).findAllById(Set.of(userId));
        verifyNoMoreInteractions(rosters,profiles,shifts,users);
    }

    @Test void emptyListDoesNotLoadReferences() {
        assertThat(service.list(null,null,null,null,null,null)).isEmpty();
        verifyNoInteractions(profiles,shifts,users);
    }

    private CreateStaffRosterRequest request(UUID shift,LocalDate rosterDate){return new CreateStaffRosterRequest(staffId,shift,rosterDate,null);}private StaffProfile staff(EmploymentStatus status){StaffProfile v=new StaffProfile();v.setId(staffId);v.setUserId(userId);v.setEmployeeCode("EMP-1");v.setEmploymentStatus(status);return v;}private ShiftDefinition shift(UUID id,String code,LocalTime start,LocalTime end,boolean crosses,boolean active){ShiftDefinition v=new ShiftDefinition();v.setId(id);v.setCode(code);v.setName(code);v.setStartTime(start);v.setEndTime(end);v.setCrossesMidnight(crosses);v.setActive(active);v.setCreatedAt(LocalDateTime.now());v.setUpdatedAt(LocalDateTime.now());return v;}private StaffRosterAssignment roster(UUID id,UUID shift,LocalDate rosterDate,RosterStatus status){StaffRosterAssignment v=new StaffRosterAssignment();v.setId(id);v.setStaffProfileId(staffId);v.setShiftDefinitionId(shift);v.setRosterDate(rosterDate);v.setStatus(status);v.setCreatedAt(LocalDateTime.now());v.setUpdatedAt(LocalDateTime.now());return v;}private StaffLeaveRequest leave(LeaveRequestStatus status,LocalDate start,LocalDate end){StaffLeaveRequest v=new StaffLeaveRequest();v.setId(UUID.randomUUID());v.setStaffProfileId(staffId);v.setStatus(status);v.setStartDate(start);v.setEndDate(end);return v;}private User user(UUID id,String name){User v=new User();v.setId(id);v.setUsername(name);v.setFullName(name);return v;}
}
