spring.application.name=casino-erp

spring.datasource.url=jdbc:postgresql://localhost:5432/casino_erp_db
spring.datasource.username=postgres
spring.datasource.password=casino@123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080